name: Deploy SAM Application

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2  # Install the AWS SAM CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Set up AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access key stored in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret key stored in GitHub Secrets
          aws-region: us-east-1  # Specify the AWS region

      - name: Build SAM application
        run: sam build --use-container  # Build the SAM application using a container

      - name: Deploy SAM application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name serverless-shift-scheduler --s3-bucket shift-scheduler-artifacts-dallas --capabilities CAPABILITY_IAM  # Deploy the SAM application
